### ISSUE TITLE
Not working on latest version

### ISSUE THREAD

**Issue by DarrenRainey** [Frayo44/Bypass-Snapchat-SSL-Certificate-Pinning#4]
Hello I cannot seem to get it to work on the latest version of Snapchat (10.52.1.0) with the latest frida-server on a rooted android 5.1 stock ROM I'm trying to use the mitmproxy-ca-cert.pem and I have tried using it both with the script as well as installing it as a user certificate for "VPN and Apps" and "WiFi" I can confirm that mitmproxy is working correctly as other SSL traffic such as Google shows up fine.

**Comment by ghost** [comment]
Yea, Snapchat changed stuff don't use this

Side note if you 100% have no other option: Downgrade to 10.4+ or spam the script to it works
